# **Selenuium**
- BeautifulSoup과 달리 파이썬 코드를 통해서 사람이 할 수 있는 웹 브라우저의 모든 기능을 제어할 수 있음
- 사람이 실제로 인터넷을 사용하는 것과 동일한 순서대로 코드를 작성해야 함
- Selenium은 동적 페이지에서도 동작하기 위해 페이지가 바뀌는 순간 모든 데이터가 초기화가 되므로 페이지의 변화에 맞게 코드를 작성해서 접근해야 함

### -> 네이버 검색, 네이버 검색 심화, 한솥도시락 크롤링

In [2]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\agnes\anaconda3\lib\site-packages (4.40.0)
Requirement already satisfied: certifi>=2026.1.4 in c:\users\agnes\anaconda3\lib\site-packages (from selenium) (2026.1.4)
Requirement already satisfied: trio<1.0,>=0.31.0 in c:\users\agnes\anaconda3\lib\site-packages (from selenium) (0.32.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in c:\users\agnes\anaconda3\lib\site-packages (from selenium) (0.12.2)
Requirement already satisfied: trio-typing>=0.10.0 in c:\users\agnes\anaconda3\lib\site-packages (from selenium) (0.10.0)
Requirement already satisfied: types-certifi>=2021.10.8.3 in c:\users\agnes\anaconda3\lib\site-packages (from selenium) (2021.10.8.3)
Requirement already satisfied: types-urllib3>=1.26.25.14 in c:\users\agnes\anaconda3\lib\site-packages (from selenium) (1.26.25.14)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in c:\users\agnes\anaconda3\lib\site-packages (from selenium) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in c:\users\agnes\anaconda3\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.6.3)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\users\agnes\anaconda3\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\agnes\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Requirement already satisfied: sortedcontainers in c:\users\agnes\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\agnes\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Requirement already satisfied: outcome in c:\users\agnes\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\agnes\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\agnes\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.0.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\agnes\anaconda3\lib\site-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\agnes\anaconda3\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\agnes\anaconda3\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (2.23)
Requirement already satisfied: mypy-extensions>=0.4.2 in c:\users\agnes\anaconda3\lib\site-packages (from trio-typing>=0.10.0->selenium) (1.0.0)
Requirement already satisfied: async-generator in c:\users\agnes\anaconda3\lib\site-packages (from trio-typing>=0.10.0->selenium) (1.10)
Requirement already satisfied: packaging in c:\users\agnes\appdata\roaming\python\python313\site-packages (from trio-typing>=0.10.0->selenium) (25.0)
Requirement already satisfied: importlib-metadata in c:\users\agnes\anaconda3\lib\site-packages (from trio-typing>=0.10.0->selenium) (8.7.0)
Requirement already satisfied: h11<1,>=0.16.0 in c:\users\agnes\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Requirement already satisfied: zipp>=3.20 in c:\users\agnes\anaconda3\lib\site-packages (from importlib-metadata->trio-typing>=0.10.0->selenium) (3.23.0)

In [2]:
# webdriver: 웹을 제어하는 클래스
from selenium import webdriver as wb
import pandas as pd

# Selenium 크롬창 제어하기
## 1) 크롬 브라우저 실행

In [9]:
driver=wb.Chrome()

- 크롬창이 뜨면 **'Chrome이 자동화된 테스트 소프트웨어에 의해 제어되고 있습니다.'** 이 문구를 항상 띄워놔야 코드로 제어할수 있음

## 2) 네이버 페이지로 이동

In [10]:
# get: driver 객체로 특정 사이트로 이동 명령
# (driver는 기본적으로 크롬 브라우저로 동작하므로 인증을 내포하고 있어 headers 설정이 필요 X)
driver.get('https://naver.com')

- Selenium의 Chrome함수로 만든 driver객체를 통해서 웹 브라우저에 연결해 있기 때문에
- 그때그때 정보를 요청하면서 화면의 HTML코드에 접근하므로 BS에서 사용한 파싱을 해줄 필요가 없음

## 3) 검색창에 특정 단어 입력
- 컴퓨터에게 검색창을 찾게 명령하기 위해서는 검색창 요소의 태그 및 선택자를 알아야 함

In [5]:
# By: selenium에서 선택자를 구분해주는 함수
from selenium.webdriver.common.by import By

In [6]:
# find_element: selenium이 지원하는 웹의 특정 하나의 요소를 찾아주는 함수
# CSS_SELECTOR: CSS 선택자를 찾아주는 인자
search = driver.find_element(By.CSS_SELECTOR, '#query')

# By.CSS_SELECTOR, '#query' 대신에 By.ID, 'query'로 작성해도 됨

In [10]:
# send_keys: 특정 문자를 입력시켜주는 함수 (여러번 실행하면 텍스트만 추가됨)
search.send_keys('트럼프')

## 4) 키보드 ENTER 누르기

In [8]:
# Keys: 키보드를 제어하는 함수
from selenium.webdriver.common.keys import Keys

In [9]:
# Keys.ENTER : 키보드 ENTER를 누르기
search.send_keys(Keys.ENTER) # Keys.에서 탭 해보면 할 수 있는 행위들 나옴

# 그 외에
# .send_keys(Keys.CONTROL, 'a'): 컨트롤+a
# Key.ESCAPE: 팝업 닫기
# Key.SPACE: 체크박스 클릭, 버튼 누르기

In [17]:
# 걍 혼자 해본 클릭해보기
# search = driver.find_element(By.CSS_SELECTOR, 'div.sds-comps-vertical-layout.sds-comps-full-layout.YyQBMfm2EIi9IKVfqqEb')
# search.click()

## **5) 이전 페이지로 가기 (뒤로가기)**

In [13]:
# 뒤로가기 버튼은 HTML 요소가 아닌 브라우저(크롬)의 고유 기능
driver.back()

## 6) 돋보기 검색 버튼으로 검색

In [14]:
search = driver.find_element(By.CSS_SELECTOR, '#query')
search.send_keys('용산 cgv')

In [18]:
btn = driver.find_element(By.CSS_SELECTOR, "#search-btn")
btn.click()    # 클릭

In [19]:
driver.back()

### XPATH 절대 경로
- XPATH는 원하는 하나의 요소에 정확히 접근하기 위한 절대 경로를 가져오는 명령
- 하나의 요소에 접근할 때 사용하면 편리하나, 여러개의 요소에 접근해야 하거나 웹 페이지가 유동적으로 변화하는환경에서는 효율이 떨어짐
- 따라서 변동이 적은 개별 고정 요소를 추출할 때 사용하거나, 요소에 ID, Class와 같은 구분자가 제대로 붙어있지 않을 때 사용하면 좋음
- HTML 코드에서 우클릭 후 copy - copy XPATH로 복사해서 사용

In [24]:
# 돋보기 버튼 클릭시 XPATH 사용
btn = driver.find_element(By.XPATH, '//*[@id="search-btn"]')
btn.click()

## 7) 스크롤 기능 사용하기
- 일반적인 웹 페이지의 내용들은 모두 body 태그 내부에 코드를 작성하게 됨
- 즉, 스크롤을 하기 위해서는 스크롤이 가능한 전체 틀인 body 태그 자체를 선택한 뒤 스크롤 기능을 활용할 수 있음

In [29]:
# TAG_NAME: 태그명으로 찾아주는 인자 
body = driver.find_element(By.TAG_NAME, 'body')

# END 키 입력(웹 페이지 화면에서 스크롤을 맨 밑으로 내리는 기능)
body.send_keys(Keys.END)

## **8) 브라우저 창 닫기**

In [30]:
# 닫기 버튼도 크롬 브라우저에서 제공하는 기본 기능
driver.quit()

### **[실습1] 네이버 검색**
1. 크롬 브라우저 켜기
2. 네이버로 접속
3. CSS_SELECTOR로 검색창 접근, 그리고 원하는 검색어 입력
4. 돋보기 검색아이콘 클릭
5. 스크롤 끝까지 내리기
6. 뒤로가기 버튼 눌러서 다시 메인으로 이동
7. 크롬 브라우저 창 종료

In [184]:
from selenium import webdriver as wb
driver = wb.Chrome()

In [185]:
driver.get("https://www.naver.com")

In [186]:
# JS = 웹사이트를 직접 조종하는 언어
# 사이트 내부 규칙 무시하고 직접 조작 

driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

In [40]:
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

search = driver.find_element(By.CSS_SELECTOR, "#query")
search.send_keys('바보')

In [41]:
click = driver.find_element(By.CSS_SELECTOR, "#search-btn")
click.click()

In [42]:
body = driver.find_element(By.TAG_NAME, 'body')
body.send_keys(Keys.END)

# 코드 한줄 지우고 싶으면 shift + delete

In [43]:
driver.back()

In [44]:
driver.quit()

### **[실습2] 네이버 검색 심화**
1. 크롬 브라우저 켜기
2. 네이버로 접속
3. CSS_SELECTOR로 검색창 접근 + 원하는 검색어 입력
4. ENTER키 사용하여 검색
5. 검색 후 상단의 '이미지' 탭클릭 (원하는대로 편하게 경로 잡기)
6. 뒤로 가기
7. '뉴스'탭클릭해서 들어가기 (CSS_SELECTOR로 경로 잡기)
8. 스크롤 맨 밑으로 내리기
9. Selenium 코드를 활용해 뉴스 기사 제목 크롤링하기 (find_elements 활용)
10. 크롤링 된 기사를 No를 1번부터 인덱스 설정하여 데이터프레임으로 만들기
11. 데이터프레임을 csv로 저장
12. 뒤로 가기 버튼 두번 실행하여 메인으로 이동
13. 크롬창 종료

In [119]:
driver = wb.Chrome()

In [120]:
driver.get("https://naver.com")

In [121]:
from selenium.webdriver.common.by import By

search = driver.find_element(By.CSS_SELECTOR, "#query")
search.send_keys('오늘')

In [122]:
search.send_keys(Keys.ENTER)

In [139]:
# 이미지 탭의 XPATH로 접근
tab = driver.find_element(By.XPATH, '//*[@id="lnb"]/div[1]/div/div[1]/div/div[1]/div[2]/a')
tab.click()

In [92]:
# CSS로 선택자 잡을거면... 
tabs = driver.find_elements(By.CSS_SELECTOR, "a.tab")
for tab in tabs:
    if tab.text == '이미지':
        tab.click()
        break

In [140]:
driver.back()

In [142]:
# 뉴스 탭 클릭하기..... 내가 볼 땐 9번째
# 계층선택자 사용하기...............
news_tab = driver.find_element(By.CSS_SELECTOR, 'div.api_flicking_wrap._conveyer_root > div.flick_bx:nth-child(9)')
news_tab.click()

In [135]:
# body 태그는 하나밖에 없으니까 find_element로 접근!

body = driver.find_element(By.TAG_NAME, 'body')
body.send_keys(Keys.END)

In [136]:
titles = driver.find_elements(By.CSS_SELECTOR, 'span.sds-comps-text.sds-comps-text-ellipsis.sds-comps-text-ellipsis-1.sds-comps-text-type-headline1')
titles[1].text

'[속보] 靑 "캄보디아 스캠조직 韓국적 피의자 73명 오늘 저녁 강제송환...'

In [137]:
len(titles)

20

In [138]:
titles_list = [i.text.strip() for i in titles]

# <위와 동일한 코드>
# news_list = []
# for i in range(len(titles)):
#     titles_list.append(titles[i].text.strip())

titles_list

['박근혜 “오늘부로 단식 멈추라” 장동혁 “그렇게 하겠다”',
 '[속보] 靑 "캄보디아 스캠조직 韓국적 피의자 73명 오늘 저녁 강제송환...',
 "대전 교제살인 장재원 오늘 1심 선고…'무기징역 구형'",
 "'직무유기' 오동운·'내란선동' 황교안, 오늘 첫 재판",
 '靑 "캄보디아 스캠조직원 73명 오늘 강제송환…역대 최대 규모"',
 '눈물 글썽인 장동혁 “더 큰 싸움 위해 단식 중단…진정한 단식은 ...',
 "[단독]與 '코스피 5000시대' 지원사격...RIA·성장펀드 법안 오늘 발의",
 '[날씨] 오늘 강추위 절정...호남 서해안·제주도 최고 7cm 눈',
 "'출근길 영하 19도' 한파 절정…전라·제주 눈 내린다[오늘날씨]",
 '장동혁 “국민들과 함께한 8일…오늘 단식 중단”',
 "오늘부터 'AI 생성물' 표시 의무…누가, 언제, 어떻게 붙이나",
 "[단독]與 '코스피 5000시대' 지원사격...RIA·성장펀드 법안 오늘 발의",
 "'내란 방조' 한덕수 오늘 선고...내란죄 첫 판단",
 '엑소 세훈, 연프앓이 "오늘부터 다 볼 것"',
 '오늘 동계올림픽 선수단 결단식…체육회 "경기에 전념할 수 있도록 지원...',
 '[날씨] 오늘 강추위 절정...호남 서해안·제주도 최고 7cm 눈',
 '대구·경북교육감 오늘 회동…행정통합 관련 현안 협의',
 '"엄마, 오늘도 산책할까?"…\'뚜벅뚜벅\' 5000보, 치매 위험 7년 늦춘다',
 "李대통령, 오늘 신년 기자회견…집권 2년 차 '대도약' 구상 제시",
 '오늘부터 AI 기본법 시행...법적 근거 마련했지만 우려 여전']

In [114]:
news_dic = {'기사 타이틀':titles_list}

df = pd.DataFrame(news_dic, index=range(1, len(titles)+1))
df.index.name = 'No'

In [115]:
df.to_csv('기사.csv', encoding='utf-8')

In [117]:
driver.back()

In [118]:
driver.quit()

# 한솥 도시락 메뉴 및 가격 정보 크롤링

In [19]:
from selenium import webdriver as wb
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from tqdm import tqdm
import pandas as pd
import time # 컴퓨터와 시간을 제어하는 모듈

In [20]:
# 크롬 브라우저 켜기
driver = wb.Chrome()

# 한솥 도시락 페이지 요청
driver.get("https://www.hsd.co.kr/menu/menu_list")

- 한솥 도시락 페이지는 **반응형 웹**으로 브라우저의 크기에 따라 보이는 요소들이 달라짐
- 그 말인즉, 페이지의 크기에 따라 내부 요소들의 구조나 경로가 바뀔 가능성이 있다는 의미
- 우리는 크롤링 시 브라우저 창을 최대화 시켜 구조 변경의 위험을 최소화하여 크롤링을 진행

In [147]:
# 브라우저 화면 최대화
driver.maximize_window()

## 메뉴 이름과 가격 수집

In [21]:
titles = driver.find_elements(By.CSS_SELECTOR, 'h4.h.fz_03')
titles[1].text
len(titles)

titles_list = [i.text.strip() for i in titles]
titles_list

['[26.01/월,화요일 할인] 행사 진달래',
 '[26.01/수,목요일 할인] 행사 돈까스도련님 고기고기',
 '[26.01/금요일 할인] 행사 김치 제육 덮밥',
 '[26.01/토요일 할인] 행사 돈까스 카레',
 '[26.01/토요일 할인] 행사 더블 돈까스도련님',
 '[26.01/일요일 할인] 행사 스팸 김치볶음밥',
 '[26.01/일요일 할인] 행사 더블 칠리 찹쌀탕수육도련님',
 '[26.01/매일 할인] 행사 단품 부대찌개',
 '[26.01/매일 할인] 행사 단품 묵은지 김치찌개',
 '[26.01/매일 할인] 행사 미니 찹쌀탕수육',
 '[26.01/매일 할인] 행사 치킨 2조각',
 '[26.01/매일 할인] 행사 토네이도 소세지',
 '[26.01/매일 할인] 행사 스팸 1개']

In [22]:
prices = driver.find_elements(By.CSS_SELECTOR, 'div.item-price')
prices[1].text
len(prices)

prices_list = [i.text.strip() for i in prices]
prices_list

['7,100원',
 '5,900원',
 '4,100원',
 '4,100원',
 '8,500원',
 '4,100원',
 '6,900원',
 '4,200원',
 '3,700원',
 '1,900원',
 '1,500원',
 '1,200원',
 '800원']

In [171]:
# HTML 요소 우클릭 - Copy - Copy selector로 태그 및선택자를 바로 가져올 수 있음
# 단, 개별 요소에 대한 내용이기 때문에 여러 데이터를 원할 때는 범위를 변경할 수 있어야 함!
# #menuList_679 > div > div.item-text > div > strong
# #menuList_680 > div > div.item-text > div > strong

In [183]:
# 맨 아래로 스크롤 내리기
body = driver.find_element(By.TAG_NAME, 'body')
body.send_keys(Keys.END)

## 더보기 버튼을 눌러 메뉴를 확장

In [23]:
btn = driver.find_element(By.CSS_SELECTOR, 'a.c_05')
btn.click()

In [180]:
# 더보기 버튼이 몇번이나 있을지 모르기 때문에 while문으로 반복 클릭

while True:
    btn = driver.find_element(By.CSS_SELECTOR, 'a.c_05')
    btn.click()
    time.sleep(2) # 2초 대기 후 반복 실행
    # 더보기 버튼을 누르고 페이지가 뜨는 시간을 기다려주는 것
    # 기다리는 시간 없이, 웹 페이지 뜨기 전에 무한정 버튼을 클릭하게 되어 과부하 걸림, 심하면 공격으로 오인해서 IP 차단될 수 있음

ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=144.0.7559.60); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#elementnotinteractableexception
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7ffe8025014c
	0x7ff701da5715
	0x7ff701da5770
	0x7ff701b50e76
	0x7ff701bad994
	0x7ff701b9efc6
	0x7ff701bd598a
	0x7ff701b9e846
	0x7ff701bf9e45
	0x7ff701b9cc28
	0x7ff701b9db33
	0x7ff70208e9f0
	0x7ff702088ded
	0x7ff7020a969a
	0x7ff701dc11e5
	0x7ff701dc99cc
	0x7ff701daebf4
	0x7ff701daeda6
	0x7ff701d94e87
	0x7ffe7d5d17ac
	0x7ffe7d5515e8
	0x7ffe8018c120

## try-except 예외 처리
- 동적 크롤링은 변수 상황이 많기 때문에 예외처리를 정말 많이 사용하게 됨
  - **try**: 일반적으로 동작하는 코드
  - **except**: try문이 동작하지 않는 예외의 경우(에러 발생시) 작동되는 코드

In [36]:
# try문: 일반적으로 동작하는 코드
try:
    # 더보기 버튼이 있으면 계속 반복 
    while True:
        btn = driver.find_element(By.CSS_SELECTOR, 'a.c_05')
        btn.click()
        time.sleep(2)
        
# except문: 에러로 try문이 동작하지 않는 예외의 경우
except:
    print("더이상 더보기 버튼이 없네요 ㅠ_ㅠ 그래도 코드는 이어서 동작합니다~!")

# 더보기 버튼을 다 누르고 난 뒤 (HTML요소를 다 받아온 뒤) 메뉴와 가격을 추출
# HTML 요소 모두 받은 뒤이므로, time.sleep을 줄 필요가 없음


titles = driver.find_elements(By.CSS_SELECTOR, 'h4.h.fz_03')
prices = driver.find_elements(By.CSS_SELECTOR, 'div.item-price > strong')
titles[-1].text, prices[-1].text

titles_list, prices_list = [], []

for i in tqdm(range(len(titles))):
    titles_list.append(titles[i].text)
    prices_list.append(prices[i].text + '원')

print('크롤링 완료!')

더이상 더보기 버튼이 없네요 ㅠ_ㅠ 그래도 코드는 이어서 동작합니다~!

100%|██████████████████████████████████████████████████████████████████████████████████| 99/99 [00:04<00:00, 24.62it/s]

크롤링 완료!

In [31]:
len(titles_list), len(prices_list)

(99, 99)

### 두개의 리스트의 요소들을 1:1로 묶어서 딕셔너리로 만들기

In [32]:
# zip: 길이가 동일한 두 개의 집합의 요소들을 1:1로 대응시켜 튜플로 묶어주는 함수
# zip 함수는 묶여진 데이터가 바로 표시되진 않아서 변수로 출력시켜도 바로 확인은 불가

temp = zip(titles_list, prices_list)
temp

In [33]:
type(temp)

zip

In [37]:
# zip 객체를 딕셔너리로 형 변환

title_price_dict = dict(zip(titles_list, prices_list))
title_price_dict

{'[26.01/월,화요일 할인] 행사 진달래': '7,100원',
 '[26.01/수,목요일 할인] 행사 돈까스도련님 고기고기': '5,900원',
 '[26.01/금요일 할인] 행사 김치 제육 덮밥': '4,100원',
 '[26.01/토요일 할인] 행사 돈까스 카레': '4,100원',
 '[26.01/토요일 할인] 행사 더블 돈까스도련님': '8,500원',
 '[26.01/일요일 할인] 행사 스팸 김치볶음밥': '4,100원',
 '[26.01/일요일 할인] 행사 더블 칠리 찹쌀탕수육도련님': '6,900원',
 '[26.01/매일 할인] 행사 단품 부대찌개': '4,200원',
 '[26.01/매일 할인] 행사 단품 묵은지 김치찌개': '3,700원',
 '[26.01/매일 할인] 행사 미니 찹쌀탕수육': '1,900원',
 '[26.01/매일 할인] 행사 치킨 2조각': '1,500원',
 '[26.01/매일 할인] 행사 토네이도 소세지': '1,200원',
 '[26.01/매일 할인] 행사 스팸 1개': '800원',
 '스페셜 한우함박스테이크 도시락': '14,000원',
 '스페셜 해바라기 도시락': '13,000원',
 '스페셜 숯불직화 진달래 도시락': '12,000원',
 '스페셜 송정식 떡갈비 도시락': '11,000원',
 '매화': '11,300원',
 '해바라기': '10,300원',
 '진달래': '8,800원',
 '새치 고기고기': '7,800원',
 '돈까스도련님 고기고기': '7,300원',
 '돈치 고기고기': '6,800원',
 '동백': '6,700원',
 '소불고기': '6,300원',
 '돈치스팸': '5,500원',
 '칠리 찹쌀탕수육도련님': '5,000원',
 '돈까스도련님': '5,200원',
 '제육 돈까스도련님': '5,200원',
 '제육볶음': '5,200원',
 '한우 함박스테이크& 청양 토네이도 소세지': '9,000원',
 '한우 함박스테이크&토네이도 소세지': '9,000원',
 '더블 돈까스도련님': '10,500원',
 '송정식 떡갈비': '7,200원',
 '더블 칠리 찹쌀탕수육도련님': '8,500원',
 '송정식 떡갈비 Ⅱ': '7,200원',
 '치킨제육': '5,500원',
 '메가치킨마요': '6,600원',
 '왕치킨마요': '5,600원',
 '빅치킨마요': '4,600원',
 '치킨마요': '3,900원',
 '메가스팸마요': '6,300원',
 '스팸마요': '4,400원',
 '참치마요': '3,800원',
 '김치볶음밥&돼지불백': '7,900원',
 '스팸 김치볶음밥': '5,200원',
 '김치볶음밥': '4,400원',
 '부대찌개': '6,500원',
 '묵은지 김치찌개': '6,000원',
 '돼지불백 덮밥': '5,900원',
 '제많덮(제육 많이 덮밥)': '6,500원',
 '빅 제많덮(빅 제육 많이 덮밥)': '7,500원',
 '숯불직화구이 덮밥': '6,500원',
 '김치 제육 덮밥': '5,200원',
 '왕카레돈까스덮밥': '6,700원',
 '오리지널 치즈 닭갈비덮밥': '6,500원',
 '김치 참치 덮밥': '4,900원',
 '핫 치즈 닭갈비덮밥': '6,500원',
 '돈까스 카레': '5,100원',
 '돈까스 덮밥': '4,700원',
 '마파두부 덮밥': '5,000원',
 '소불고기 감초고추장 비빔밥': '6,000원',
 '시골제육 두부강된장 비빔밥': '6,500원',
 '참치야채 감초고추장 비빔밥': '4,000원',
 '빅치킨마요 부대찌개 정식': '8,800원',
 '치킨마요 부대찌개 정식': '8,100원',
 '단품 부대찌개': '5,200원',
 '단품 묵은지 김치찌개': '4,700원',
 '단품 카레': '2,900원',
 '반찬 돈까스도련님': '4,200원',
 '반찬 치킨': '4,000원',
 '반찬 제육볶음': '3,900원',
 '반찬 돈까스': '2,900원',
 '반찬 토네이도 소세지': '3,200원',
 '반찬 고기고기': '3,900원',
 '반찬 고등어 데리야끼': '3,900원',
 '미니반찬 김치': '500원',
 '미니반찬 무말랭이 무침': '600원',
 '12곡밥': '2,100원',
 '발아현미밥': '1,900원',
 '한솥밥': '1,200원',
 '해시 포테이토 스틱': '2,000원',
 '치즈버터 해시 포테이토 스틱': '2,200원',
 '허니버터 해시 포테이토 스틱': '2,200원',
 '뉴 감자고로케': '2,700원',
 '미니 찹쌀핫도그': '2,800원',
 '미니 찹쌀탕수육': '2,300원',
 '케이준후라이': '1,900원',
 '김피탕': '6,700원',
 '크림 닭강정(소)': '3,900원',
 '크림 닭강정(중)': '9,900원',
 '한솥 닭강정(소)': '3,500원',
 '한솥 닭강정(중)': '9,000원',
 '후라이드 순살(소)_양념치킨소스': '4,000원',
 '후라이드 순살(소)_케이준소스': '4,000원',
 '후라이드 순살(중)': '7,500원',
 '치킹 반반순살(양념, 후라이드)': '16,900원',
 '치킹 반반순살(후라이드)': '16,900원',
 '제주녹차 미니꿀호떡': '2,500원'}

# 여태까지 작성한 코드를 한 셀로 동작시키기
- 만약 웹 크롤러를 개발하고 실행파일을 만들어서 배포한다면 한 셀에 시작부터 끝까지 코드가 모두 들어가 있어야 함!

In [44]:

#     from selenium import webdriver as wb
#     from selenium.webdriver.common.by import By
#     from selenium.webdriver.common.keys import Keys
#     from tqdm import tqdm
#     import pandas as pd
#     import time

driver = wb.Chrome()
driver.get("https://www.hsd.co.kr/menu/menu_list")
time.sleep(1)
driver.maximize_window()
time.sleep(1)

try:
    while True:
        btn = driver.find_element(By.CSS_SELECTOR, 'a.c_05')
        btn.click()
        time.sleep(2)
except:
    print("더이상 더보기 버튼이 없네요 ㅠ_ㅠ 그래도 코드는 이어서 동작합니다~!")

titles = driver.find_elements(By.CSS_SELECTOR, 'h4.h.fz_03')
prices = driver.find_elements(By.CSS_SELECTOR, 'div.item-price > strong')

# titles_list = [i.text.strip() for i in titles]
# prices_list = [i.text.strip() for i in prices]

titles_list, prices_list = [], []

for i in tqdm(range(len(titles))):
    titles_list.append(titles[i].text)
    prices_list.append(prices[i].text + '원')

print('크롤링 완료!')
print('메뉴 개수:', len(titles_list))
print('가격 개수:', len(prices_list))

hansot_dic = {"메뉴명": titles_list, "가격": prices_list}

hansot_df = pd.DataFrame(hansot_dic, index=range(1,len(titles_list)+1))
hansot_df.index.name = 'No.'
hansot_df

더이상 더보기 버튼이 없네요 ㅠ_ㅠ 그래도 코드는 이어서 동작합니다~!

100%|██████████████████████████████████████████████████████████████████████████████████| 99/99 [00:02<00:00, 40.36it/s]

크롤링 완료!
메뉴 개수: 99
가격 개수: 99

                                  메뉴명       가격
No.
1             [26.01/월,화요일 할인] 행사 진달래   7,100원
2     [26.01/수,목요일 할인] 행사 돈까스도련님 고기고기   5,900원
3          [26.01/금요일 할인] 행사 김치 제육 덮밥   4,100원
4            [26.01/토요일 할인] 행사 돈까스 카레   4,100원
5         [26.01/토요일 할인] 행사 더블 돈까스도련님   8,500원
6          [26.01/일요일 할인] 행사 스팸 김치볶음밥   4,100원
7    [26.01/일요일 할인] 행사 더블 칠리 찹쌀탕수육도련님   6,900원
8            [26.01/매일 할인] 행사 단품 부대찌개   4,200원
9        [26.01/매일 할인] 행사 단품 묵은지 김치찌개   3,700원
10          [26.01/매일 할인] 행사 미니 찹쌀탕수육   1,900원
11            [26.01/매일 할인] 행사 치킨 2조각   1,500원
12          [26.01/매일 할인] 행사 토네이도 소세지   1,200원
13             [26.01/매일 할인] 행사 스팸 1개     800원
14                   스페셜 한우함박스테이크 도시락  14,000원
15                       스페셜 해바라기 도시락  13,000원
16                   스페셜 숯불직화 진달래 도시락  12,000원
17                    스페셜 송정식 떡갈비 도시락  11,000원
18                                 매화  11,300원
19                               해바라기  10,300원
20                                진달래   8,800원
21                            새치 고기고기   7,800원
22                        돈까스도련님 고기고기   7,300원
23                            돈치 고기고기   6,800원
24                                 동백   6,700원
25                               소불고기   6,300원
26                               돈치스팸   5,500원
27                        칠리 찹쌀탕수육도련님   5,000원
28                             돈까스도련님   5,200원
29                          제육 돈까스도련님   5,200원
30                               제육볶음   5,200원
31             한우 함박스테이크& 청양 토네이도 소세지   9,000원
32                 한우 함박스테이크&토네이도 소세지   9,000원
33                          더블 돈까스도련님  10,500원
34                            송정식 떡갈비   7,200원
35                     더블 칠리 찹쌀탕수육도련님   8,500원
36                          송정식 떡갈비 Ⅱ   7,200원
37                               치킨제육   5,500원
38                             메가치킨마요   6,600원
39                              왕치킨마요   5,600원
40                              빅치킨마요   4,600원
41                               치킨마요   3,900원
42                             메가스팸마요   6,300원
43                               스팸마요   4,400원
44                               참치마요   3,800원
45                         김치볶음밥&돼지불백   7,900원
46                           스팸 김치볶음밥   5,200원
47                              김치볶음밥   4,400원
48                               부대찌개   6,500원
49                           묵은지 김치찌개   6,000원
50                            돼지불백 덮밥   5,900원
51                      제많덮(제육 많이 덮밥)   6,500원
52                  빅 제많덮(빅 제육 많이 덮밥)   7,500원
53                          숯불직화구이 덮밥   6,500원
54                           김치 제육 덮밥   5,200원
55                           왕카레돈까스덮밥   6,700원
56                      오리지널 치즈 닭갈비덮밥   6,500원
57                           김치 참치 덮밥   4,900원
58                         핫 치즈 닭갈비덮밥   6,500원
59                             돈까스 카레   5,100원
60                             돈까스 덮밥   4,700원
61                            마파두부 덮밥   5,000원
62                     소불고기 감초고추장 비빔밥   6,000원
63                     시골제육 두부강된장 비빔밥   6,500원
64                     참치야채 감초고추장 비빔밥   4,000원
65                      빅치킨마요 부대찌개 정식   8,800원
66                       치킨마요 부대찌개 정식   8,100원
67                            단품 부대찌개   5,200원
68                        단품 묵은지 김치찌개   4,700원
69                              단품 카레   2,900원
70                          반찬 돈까스도련님   4,200원
71                              반찬 치킨   4,000원
72                            반찬 제육볶음   3,900원
73                             반찬 돈까스   2,900원
74                        반찬 토네이도 소세지   3,200원
75                            반찬 고기고기   3,900원
76                        반찬 고등어 데리야끼   3,900원
77                            미니반찬 김치     500원
78                       미니반찬 무말랭이 무침     600원
79                               12곡밥   2,100원
80                              발아현미밥   1,900원
81                                한솥밥   1,200원
82                         해시 포테이토 스틱   2,000원
83                    치즈버터 해시 포테이토 스틱   2,200원
84                    허니버터 해시 포테이토 스틱   2,200원
85                            뉴 감자고로케   2,700원
86                           미니 찹쌀핫도그   2,800원
87                           미니 찹쌀탕수육   2,300원
88                             케이준후라이   1,900원
89                                김피탕   6,700원
90                          크림 닭강정(소)   3,900원
91                          크림 닭강정(중)   9,900원
92                          한솥 닭강정(소)   3,500원
93                          한솥 닭강정(중)   9,000원
94                  후라이드 순살(소)_양념치킨소스   4,000원
95                   후라이드 순살(소)_케이준소스   4,000원
96                         후라이드 순살(중)   7,500원
97                  치킹 반반순살(양념, 후라이드)  16,900원
98                      치킹 반반순살(후라이드)  16,900원
99                         제주녹차 미니꿀호떡   2,500원

In [45]:
# set_option('display.max_rows') : DF의 최대 출력 행을 설정
# None의 의미는 모든 행을 출력하겠다는 뜻 (수치를 입력하면 해당 수치만큼만 표시됨)
pd.set_option('display.max_rows', None)
hansot_df


# set_option('display.max_columns', None) 모든 컬럼을 다 보겠다는 의미!
# pd.reset_option('display')는 설정한 옵션을 다시 초기화시키는 것

                                  메뉴명       가격
No.
1             [26.01/월,화요일 할인] 행사 진달래   7,100원
2     [26.01/수,목요일 할인] 행사 돈까스도련님 고기고기   5,900원
3          [26.01/금요일 할인] 행사 김치 제육 덮밥   4,100원
4            [26.01/토요일 할인] 행사 돈까스 카레   4,100원
5         [26.01/토요일 할인] 행사 더블 돈까스도련님   8,500원
6          [26.01/일요일 할인] 행사 스팸 김치볶음밥   4,100원
7    [26.01/일요일 할인] 행사 더블 칠리 찹쌀탕수육도련님   6,900원
8            [26.01/매일 할인] 행사 단품 부대찌개   4,200원
9        [26.01/매일 할인] 행사 단품 묵은지 김치찌개   3,700원
10          [26.01/매일 할인] 행사 미니 찹쌀탕수육   1,900원
11            [26.01/매일 할인] 행사 치킨 2조각   1,500원
12          [26.01/매일 할인] 행사 토네이도 소세지   1,200원
13             [26.01/매일 할인] 행사 스팸 1개     800원
14                   스페셜 한우함박스테이크 도시락  14,000원
15                       스페셜 해바라기 도시락  13,000원
16                   스페셜 숯불직화 진달래 도시락  12,000원
17                    스페셜 송정식 떡갈비 도시락  11,000원
18                                 매화  11,300원
19                               해바라기  10,300원
20                                진달래   8,800원
21                            새치 고기고기   7,800원
22                        돈까스도련님 고기고기   7,300원
23                            돈치 고기고기   6,800원
24                                 동백   6,700원
25                               소불고기   6,300원
26                               돈치스팸   5,500원
27                        칠리 찹쌀탕수육도련님   5,000원
28                             돈까스도련님   5,200원
29                          제육 돈까스도련님   5,200원
30                               제육볶음   5,200원
31             한우 함박스테이크& 청양 토네이도 소세지   9,000원
32                 한우 함박스테이크&토네이도 소세지   9,000원
33                          더블 돈까스도련님  10,500원
34                            송정식 떡갈비   7,200원
35                     더블 칠리 찹쌀탕수육도련님   8,500원
36                          송정식 떡갈비 Ⅱ   7,200원
37                               치킨제육   5,500원
38                             메가치킨마요   6,600원
39                              왕치킨마요   5,600원
40                              빅치킨마요   4,600원
41                               치킨마요   3,900원
42                             메가스팸마요   6,300원
43                               스팸마요   4,400원
44                               참치마요   3,800원
45                         김치볶음밥&돼지불백   7,900원
46                           스팸 김치볶음밥   5,200원
47                              김치볶음밥   4,400원
48                               부대찌개   6,500원
49                           묵은지 김치찌개   6,000원
50                            돼지불백 덮밥   5,900원
51                      제많덮(제육 많이 덮밥)   6,500원
52                  빅 제많덮(빅 제육 많이 덮밥)   7,500원
53                          숯불직화구이 덮밥   6,500원
54                           김치 제육 덮밥   5,200원
55                           왕카레돈까스덮밥   6,700원
56                      오리지널 치즈 닭갈비덮밥   6,500원
57                           김치 참치 덮밥   4,900원
58                         핫 치즈 닭갈비덮밥   6,500원
59                             돈까스 카레   5,100원
60                             돈까스 덮밥   4,700원
61                            마파두부 덮밥   5,000원
62                     소불고기 감초고추장 비빔밥   6,000원
63                     시골제육 두부강된장 비빔밥   6,500원
64                     참치야채 감초고추장 비빔밥   4,000원
65                      빅치킨마요 부대찌개 정식   8,800원
66                       치킨마요 부대찌개 정식   8,100원
67                            단품 부대찌개   5,200원
68                        단품 묵은지 김치찌개   4,700원
69                              단품 카레   2,900원
70                          반찬 돈까스도련님   4,200원
71                              반찬 치킨   4,000원
72                            반찬 제육볶음   3,900원
73                             반찬 돈까스   2,900원
74                        반찬 토네이도 소세지   3,200원
75                            반찬 고기고기   3,900원
76                        반찬 고등어 데리야끼   3,900원
77                            미니반찬 김치     500원
78                       미니반찬 무말랭이 무침     600원
79                               12곡밥   2,100원
80                              발아현미밥   1,900원
81                                한솥밥   1,200원
82                         해시 포테이토 스틱   2,000원
83                    치즈버터 해시 포테이토 스틱   2,200원
84                    허니버터 해시 포테이토 스틱   2,200원
85                            뉴 감자고로케   2,700원
86                           미니 찹쌀핫도그   2,800원
87                           미니 찹쌀탕수육   2,300원
88                             케이준후라이   1,900원
89                                김피탕   6,700원
90                          크림 닭강정(소)   3,900원
91                          크림 닭강정(중)   9,900원
92                          한솥 닭강정(소)   3,500원
93                          한솥 닭강정(중)   9,000원
94                  후라이드 순살(소)_양념치킨소스   4,000원
95                   후라이드 순살(소)_케이준소스   4,000원
96                         후라이드 순살(중)   7,500원
97                  치킹 반반순살(양념, 후라이드)  16,900원
98                      치킹 반반순살(후라이드)  16,900원
99                         제주녹차 미니꿀호떡   2,500원